//Main Component
export const PHONE_LIST_FETCHED = "SN_MAIN_COMP#PHONE_LIST_FETCHED";
export const PHONE_SELECTED = "SN_MAIN_COMP#PHONE_SELECTED";

//Phone Card component
export const PHONE_CARD_SELECTED = "SN_MAIN_COMP#PHONE_CARD_SELECTED";

//Cart component
export const CHECKOUT_CLICKED = "SN_MAIN_COMP#CHECKOUT_CLICKED";
export const QUANTITY_CHANGED = "SN_MAIN_COMP#QUANTITY_CHANGED";
